# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\2022-1\graduate_design\RedPanda\RedPanda\widgets\DocView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DocView(object):
    def setupUi(self, DocView):
        DocView.setObjectName("DocView")
        DocView.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(DocView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(DocView)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.treeWidget = ModelTree(DocView)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.treeWidget)

        self.retranslateUi(DocView)
        QtCore.QMetaObject.connectSlotsByName(DocView)

    def retranslateUi(self, DocView):
        _translate = QtCore.QCoreApplication.translate
        DocView.setWindowTitle(_translate("DocView", "Form"))
        self.lineEdit.setPlaceholderText(_translate("DocView", "Search"))
from RedPanda.widgets.Logic_DocTree import ModelTree
